### ISSUE TITLE
get_space_group_number fails

### ISSUE THREAD

**Issue by ssteinma** [ulissigroup/wherewulff#14]
Dear Developers,
I would like to use wherewulff, but I fail to obtain a working package.
In particular, even for trivial tests (RuO2), I obtain the following error:
```
Traceback (most recent call last):
  File "/XXX/anaconda3/envs/wherewulff/lib/python3.8/site-packages/pymatgen/transformations/advanced_transformations.py", line 948, in apply_transformation
    for _, g in groupby(sorted((d["structure"] for d in alls), key=key), key):
  File "/XXX/anaconda3/envs/wherewulff/lib/python3.8/site-packages/pymatgen/transformations/advanced_transformations.py", line 945, in key
    return SpacegroupAnalyzer(x, 0.1).get_space_group_number()
  File "/XXX/anaconda3/envs/wherewulff/lib/python3.8/site-packages/pymatgen/symmetry/analyzer.py", line 110, in get_space_group_number
    print(int(self._space_group_data["number"]))
TypeError: 'NoneType' object is not subscriptable
```
I am not entirely sure, but I am tempted to blame spglib, in the spirit of the following issue (which is supposed to be resolved, though)
https://github.com/materialsproject/pymatgen/issues/1113

We are using spglib 2.0.2, but I would love to know which version you are using, maybe this would allow us to reach a functional version...

**Comment by ssteinma** [comment]
I am still not entirely sure where the problem comes from, but, what I know by now is that the conda environment is challenging to setup with the current libraries: atomate is not developed anymore, but the materials project related codes evolve quite quickly. To make a long story short, I had to make several manual adjustments, but still do not have a well-working version.
Maybe it would be helpful to post your versions of the dependencies, especially for atomate, custodian, fireworks and pymatgen.

**Comment by yurisanspeur** [comment]
@ssteinma Thanks for all the feedback! I believe we have solved the environment issue. I also haven't forgotten about your feature request of ingesting structure objects directly instead of loading from cif files so that more metadata can be loaded and there is better communication between the bulk workflow and WhereWulff. Things have been a little bit crazy on my end but I will get to it! Thanks!
